### ISSUE TITLE
关于html的 font-size的问题

### ISSUE THREAD

**Issue by igfz** [frozenui/frozenui#128]
html {  font-size:85.33333px  }
我都看到官方 forzen.css中，有设定html的font-size，我知道这是是用来初始化浏览器字体大小的，但是我不知道具体在此框架中有什么用。我了解的情况是，如果子元素用到rem，html的font-size才有效，但是我检索了一下forzen.css 发现里面根本没有用到rem的单位，是预留的吗？望解答。

**Comment by ccJUN** [comment]
已经加上了对rem的支持，具体可以参考frozen/base/rem.scss
