### ISSUE TITLE
FrozenUI官网首页错误

### ISSUE THREAD

**Issue by zhuangjinxin** [frozenui/frozenui#149]
官网首页 特色展示部分：
使用iconfont展示图标，包含了按钮，列表，表单，提示，弹窗等常用组件，新增文本，布局，1px，rem，文字截断，占位，两端留白，两端对齐等解决方案，同时解决了```手极端```屏幕适配问题。

问题描述：
1.```手极端```明显是笔误，改成```手机端```；
2.这段话被手机展示模块覆盖了一部分，布局有问题；

请抓紧时间更改这些明显的错误！

**Comment by airyland** [comment]
FronzenUI貌似已经很多没人维护了吧。

**Comment by zhuangjinxin** [comment]
可惜了，这套设计规范个人感觉非常好，常用的移动端组件基本上都有，而且样式也不错。

**Comment by fayching** [comment]
已解决，谢谢反馈
