### ISSUE TITLE
页面无法向下滑动

### ISSUE THREAD

**Issue by julor** [frozenui/frozenui#16]
若ui-list有多个，超过一个页面时，设置成scrollY: true，但是还是无法滑动到ui-btn部分，难道我用的姿势不对？
code:
![deepinscreenshot20150106153250](https://cloud.githubusercontent.com/assets/5569850/5625607/661ec3d2-95b9-11e4-9b41-50a28611cfc9.png)

**Comment by hahnzhu** [comment]
可以上个 Demo 吗？

**Comment by julor** [comment]
是我的自己的原因，不好意思
