### ISSUE TITLE
Firefox下不忍直视啊~

### ISSUE THREAD

**Issue by ycjcl868** [frozenui/frozenui#166]
![image](https://cloud.githubusercontent.com/assets/13595509/21849513/1f14a642-d841-11e6-8205-2d8b99f06e47.png)

**Comment by webtsp** [comment]
移动端的UI库你在电脑版Firefox上测试有意义？

**Comment by ycjcl868** [comment]
2017年的 issue，昨天才回复，还有意义吗？
