### ISSUE TITLE
这个项目是不是不维护了

### ISSUE THREAD

**Issue by karma-sun** [frozenui/frozenui#194]
这个项目是不是不维护了，大半年没有更新

**Comment by hayye** [comment]
QQ这么长时间，界面也没什么变化啊

**Comment by postunit** [comment]
没经常更新说明稳定，这个也是QQ的团队开发的，一般更新应该也是大版本，目前用2.0.0没啥问题

**Comment by leaf2006** [comment]
应该是目前不维护了……现在都还挺稳定……现在最近更新已经是3 years ago了……
