### ISSUE TITLE
radio使用伪元素无法由js控制怎么办？

### ISSUE THREAD

**Issue by zoraShi** [frozenui/frozenui#32]

**Comment by fayching** [comment]
样式是用的伪类，但是切换还是用的checked属性的

**Comment by zoraShi** [comment]
默认的直接写在标签上的checked属性是好用的，但是用jquery或者js动态在加载后控制的，貌似就不行了

**Comment by zoraShi** [comment]
点击变化的时候html的checked属性也没有变化，可以开启F12查看

**Comment by fayching** [comment]
@zoraShi 要修改checked属性不能改attr，要改prop，这是HTML的属性分为attribute和property不同造成的。

**Comment by zoraShi** [comment]
成功了，谢谢
